server:
  port: 8080

spring:
  application:
    name: legacy-project-b

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.web.filter: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
